import type { QualityCase, QualitySuite } from './quality.types.ts'

const single = (pairs: [query: string, expected: string][]): QualityCase[] =>
  pairs.map(([query, expected]) => ({ query, relevant: [expected] }))

/**
 * Hand-labeled query sets used by the quality tests and the ranking report.
 *
 * 품질 테스트와 랭킹 리포트에서 사용하는 수작업 레이블 쿼리셋.
 *
 * Lexical suites (`mustPass: true`) cover the matching tiers and must always
 * find their emoji. Intent suites (`mustPass: false`) hold everyday queries a
 * user types when they know the feeling or situation but not the emoji name —
 * including ones that fail today — and are tracked by metrics only.
 *
 * Held-out suites were written without access to the search data or the other
 * suites, and data changes must be made without reading them, so they measure
 * generalization rather than coverage of known queries.
 */
export const QUALITY_SUITES: QualitySuite[] = [
  {
    name: 'Exact English',
    mustPass: true,
    cases: single([
      ['apple', '🍎'],
      ['fire', '🔥'],
      ['heart', '❤️'],
      ['dog', '🐶'],
      ['cat', '🐱'],
      ['rocket', '🚀'],
      ['pizza', '🍕'],
      ['beer', '🍺'],
      ['star', '⭐'],
      ['music', '🎵'],
      ['camera', '📷'],
      ['coffee', '☕'],
      ['rain', '🌧️'],
      ['snow', '❄️'],
      ['basketball', '🏀'],
    ]),
  },
  {
    name: 'Typo (distance 1)',
    mustPass: true,
    cases: single([
      ['aple', '🍎'],
      ['fore', '🔥'],
      ['roket', '🚀'],
      ['piza', '🍕'],
      ['ber', '🍺'],
      ['cofee', '☕'],
      ['camra', '📷'],
      ['musi', '🎵'],
      ['rein', '🌧️'],
      ['snw', '❄️'],
    ]),
  },
  {
    name: 'Typo (distance 2)',
    mustPass: true,
    cases: single([
      ['appel', '🍎'],
      ['rcket', '🚀'],
      ['pizz', '🍕'],
      ['coffe', '☕'],
      ['cmaera', '📷'],
    ]),
  },
  {
    name: 'Korean exact',
    mustPass: true,
    cases: single([
      ['사과', '🍎'],
      ['강아지', '🐶'],
      ['고양이', '🐱'],
      ['커피', '☕'],
      ['축구', '⚽'],
      ['피자', '🍕'],
      ['사랑', '❤️'],
      ['불', '🔥'],
      ['하트', '❤️'],
      ['맥주', '🍺'],
      ['치킨', '🍗'],
      ['로켓', '🚀'],
      ['별', '⭐'],
      ['음악', '🎵'],
      ['카메라', '📷'],
    ]),
  },
  {
    name: 'Korean choseong',
    mustPass: true,
    cases: single([
      ['ㅅㄱ', '🍎'],
      ['ㄱㅇㅈ', '🐶'],
      ['ㄱㅇㅇ', '🐱'],
      ['ㅋㅍ', '☕'],
      ['ㅊㄱ', '⚽'],
      ['ㅍㅈ', '🍕'],
      ['ㅅㄹ', '❤️'],
      ['ㅎㅌ', '❤️'],
      ['ㅁㅈ', '🍺'],
      ['ㅊㅋ', '🍗'],
    ]),
  },
  {
    name: 'Korean partial choseong',
    mustPass: true,
    cases: single([
      ['사ㄱ', '🍎'],
      ['강ㅇㅈ', '🐶'],
      ['고ㅇㅇ', '🐱'],
      ['커ㅍ', '☕'],
      ['축ㄱ', '⚽'],
    ]),
  },
  {
    name: 'Concept (English)',
    mustPass: true,
    cases: single([
      ['celebration', '🎉'],
      ['sleepy', '😴'],
      ['money', '💰'],
      ['deadline', '⏰'],
      ['workout', '💪'],
      ['spooky', '👻'],
      ['perfect', '💯'],
      ['birthday', '🎂'],
      ['goodnight', '🌙'],
      ['luck', '🍀'],
    ]),
  },
  {
    name: 'Concept (Korean)',
    mustPass: true,
    cases: single([
      ['축하', '🎉'],
      ['졸림', '😴'],
      ['돈', '💰'],
      ['마감', '⏰'],
      ['운동', '💪'],
      ['생일', '🎂'],
      ['행운', '🍀'],
    ]),
  },
  {
    name: 'Concept (Korean choseong)',
    mustPass: true,
    cases: single([
      ['ㅊㅎ', '🎉'],
      ['ㅅㅇ', '🎂'],
    ]),
  },
  {
    name: 'Intent (English)',
    mustPass: false,
    cases: [
      { query: 'lol', relevant: ['😂', '🤣'] },
      { query: 'congrats', relevant: ['🎉', '🥳', '🎊'] },
      { query: 'thanks', relevant: ['🙏', '🥹'] },
      { query: 'sorry', relevant: ['🙏', '😔', '🥺'] },
      { query: 'hungry', relevant: ['🤤', '🍔', '🍕', '🍽️'] },
      { query: 'crying', relevant: ['😭', '😢'] },
      { query: 'nervous', relevant: ['😰', '😬', '😥'] },
      { query: 'mind blown', relevant: ['🤯'] },
      { query: 'good job', relevant: ['👍', '👏', '💯'] },
      { query: 'agree', relevant: ['👍', '🙆', '💯'] },
      { query: 'hello', relevant: ['👋'] },
      { query: 'bye', relevant: ['👋'] },
      { query: 'shrug', relevant: ['🤷'] },
      { query: 'hug', relevant: ['🤗', '🫂'] },
      { query: 'suspicious', relevant: ['🤨', '🧐'] },
      { query: 'annoyed', relevant: ['😤', '😒', '😑'] },
      { query: 'weekend', relevant: ['🎉', '😎', '🛋️'] },
      { query: 'monday', relevant: ['😩', '😫', '☕'] },
      { query: 'vacation', relevant: ['🏖️', '🌴', '✈️'] },
      { query: 'overtime', relevant: ['💻', '😩', '🌙'] },
      { query: 'diet', relevant: ['🥗', '💪'] },
      { query: 'rip', relevant: ['🪦', '💀', '⚰️'] },
      { query: 'cheers', relevant: ['🍻', '🥂'] },
      { query: 'good luck', relevant: ['🍀', '🤞'] },
      { query: 'love you', relevant: ['❤️', '🥰', '😘'] },
    ],
  },
  {
    name: 'Intent (Korean)',
    mustPass: false,
    cases: [
      { query: 'ㅋㅋ', relevant: ['😂', '🤣'] },
      { query: '웃겨', relevant: ['😂', '🤣'] },
      { query: '고마워', relevant: ['🙏', '🥹'] },
      { query: '미안', relevant: ['🙏', '😔', '🥺'] },
      { query: '배고파', relevant: ['🤤', '🍔', '🍕', '🍽️'] },
      { query: '눈물', relevant: ['😭', '😢'] },
      { query: '긴장', relevant: ['😰', '😬', '😥'] },
      { query: '헐', relevant: ['😱', '😲', '🤯'] },
      { query: '멘붕', relevant: ['🤯', '😵', '😵‍💫'] },
      { query: '잘했어', relevant: ['👍', '👏', '💯'] },
      { query: '화이팅', relevant: ['💪', '🔥', '📣'] },
      { query: '안녕', relevant: ['👋'] },
      { query: '좋아요', relevant: ['👍', '❤️'] },
      { query: '싫어', relevant: ['👎', '🙅', '😒'] },
      { query: '짜증', relevant: ['😤', '😠', '😒'] },
      { query: '뿌듯', relevant: ['😌', '💪', '😎'] },
      { query: '퇴근', relevant: ['🏃', '🎉', '🍺'] },
      { query: '출근', relevant: ['💼', '🏢', '😩'] },
      { query: '월요일', relevant: ['😩', '😫', '☕'] },
      { query: '주말', relevant: ['🎉', '😎', '🛋️'] },
      { query: '휴가', relevant: ['🏖️', '🌴', '✈️'] },
      { query: '야근', relevant: ['💻', '😩', '🌙'] },
      { query: '다이어트', relevant: ['🥗', '💪'] },
      { query: '더워', relevant: ['🥵', '☀️'] },
      { query: '합격', relevant: ['🎉', '🥳', '💯'] },
    ],
  },
  {
    name: 'Held-out intent (English)',
    mustPass: false,
    cases: [
      { query: 'hungry', relevant: ['🤤', '😋', '🍽️'] },
      { query: 'sleepy', relevant: ['😴', '🥱', '😪'] },
      { query: 'exhausted', relevant: ['😩', '😫', '😮‍💨'] },
      { query: 'lol', relevant: ['😂', '🤣', '😆'] },
      { query: 'omg', relevant: ['😱', '😲', '😮'] },
      { query: 'congrats', relevant: ['🎉', '🥳', '🎊', '👏'] },
      { query: 'thank you', relevant: ['🙏', '😊', '🥰'] },
      { query: 'sorry', relevant: ['🙏', '😔', '🥺'] },
      { query: 'love you', relevant: ['❤️', '🥰', '😘', '💕'] },
      { query: 'miss you', relevant: ['🥺', '😢', '💕'] },
      { query: 'good night', relevant: ['🌙', '😴', '💤'] },
      { query: 'good morning', relevant: ['🌞', '☀️', '🌅'] },
      { query: "it's raining", relevant: ['☔', '🌧️', '☂️'] },
      { query: 'so hot', relevant: ['🥵', '☀️', '🔥'] },
      { query: 'freezing', relevant: ['🥶', '❄️'] },
      { query: 'party', relevant: ['🎉', '🥳', '🎊', '🪩'] },
      { query: 'angry', relevant: ['😠', '😡', '😤', '💢'] },
      { query: 'ugh', relevant: ['😩', '😒', '🙄', '😤'] },
      { query: 'cringe', relevant: ['😬', '🫣', '😖'] },
      { query: 'awkward', relevant: ['😬', '😅'] },
      { query: 'mind blown', relevant: ['🤯'] },
      { query: 'good luck', relevant: ['🍀', '🤞', '💪'] },
      { query: 'lit', relevant: ['🔥', '🥳'] },
      { query: 'slay', relevant: ['💅', '🔥', '👑'] },
      { query: 'sus', relevant: ['🤨', '🧐', '👀'] },
      { query: 'bored', relevant: ['🥱', '😑', '😐'] },
      { query: 'nervous', relevant: ['😰', '😬', '😅', '😓'] },
      { query: 'payday', relevant: ['💰', '🤑', '💸', '💵'] },
      { query: 'hugs', relevant: ['🤗', '🫂'] },
      { query: 'so cute', relevant: ['🥰', '😍', '🥹'] },
    ],
  },
  {
    name: 'Held-out intent (Korean)',
    mustPass: false,
    cases: [
      { query: '배고파', relevant: ['🤤', '😋', '🍽️'] },
      { query: '졸려', relevant: ['😴', '🥱', '😪'] },
      { query: '퇴근하고 싶다', relevant: ['😩', '😫', '🏃'] },
      { query: '야근 중', relevant: ['😫', '💻', '🌃'] },
      { query: '짜증나', relevant: ['😤', '😠', '😡', '💢'] },
      { query: '대박', relevant: ['😲', '🤯', '👍', '🔥'] },
      { query: 'ㅋㅋㅋ', relevant: ['😂', '🤣', '😆'] },
      { query: '헐', relevant: ['😱', '😲', '😮'] },
      { query: '고마워', relevant: ['🙏', '😊', '🥰'] },
      { query: '미안해', relevant: ['🙏', '🥺', '😢', '🙇'] },
      { query: '축하해', relevant: ['🎉', '🥳', '🎊', '👏'] },
      { query: '사랑해', relevant: ['❤️', '🥰', '😘', '💕'] },
      { query: '보고싶어', relevant: ['🥺', '😢', '💕'] },
      { query: '비 온다', relevant: ['☔', '🌧️', '☂️'] },
      { query: '너무 덥다', relevant: ['🥵', '☀️', '🔥'] },
      { query: '추워', relevant: ['🥶', '❄️', '☃️'] },
      { query: '치킨 땡긴다', relevant: ['🍗', '🤤'] },
      { query: '술 한잔', relevant: ['🍺', '🍻', '🍶', '🥂'] },
      { query: '커피 수혈', relevant: ['☕'] },
      { query: '화이팅', relevant: ['💪', '🔥', '👊', '✊'] },
      { query: '오운완', relevant: ['💪', '🏋️', '🏃'] },
      { query: '멘붕', relevant: ['🤯', '😵', '😱'] },
      { query: '설렌다', relevant: ['🥰', '😍', '💓', '💗'] },
      { query: '부끄러워', relevant: ['😳', '☺️', '🙈'] },
      { query: '어이없네', relevant: ['🙄', '😑', '🤦'] },
      { query: '킹받네', relevant: ['😤', '😡', '💢'] },
      { query: '월요병', relevant: ['😩', '😫', '😵‍💫'] },
      { query: '월급날', relevant: ['💰', '💸', '🤑', '💵'] },
      { query: '합격했어', relevant: ['🎉', '🥳', '🎊', '🙌'] },
      { query: '시험 망했다', relevant: ['😭', '😵', '📉', '💀'] },
      { query: '감기 걸렸어', relevant: ['🤧', '🤒', '😷'] },
      { query: '잘자', relevant: ['🌙', '😴', '💤'] },
      { query: '좋은 아침', relevant: ['🌞', '☀️', '🌅'] },
      { query: '여행 가고싶다', relevant: ['✈️', '🏖️', '🧳', '🌴'] },
      { query: '개웃겨', relevant: ['🤣', '😂'] },
      { query: 'ㅠㅠ', relevant: ['😭', '😢', '🥲'] },
      { query: '노잼', relevant: ['😑', '😐', '🥱'] },
      { query: '불금', relevant: ['🎉', '🍻', '🥳', '🔥'] },
      { query: '현타', relevant: ['😶', '😑', '🫠'] },
      { query: '소름 돋아', relevant: ['😱', '😨'] },
    ],
  },
]
