import { describe, expect, test } from 'vitest'
import type { EmojiTable } from './build-emoji-table.ts'
import type { InvertedIndex } from './build-inverted-index.ts'
import { serializeAsTsModule } from './serialize.ts'

const sampleTable: EmojiTable = {
  emojis: [
    ['🍎', 'red apple', 0],
    ['🍏', 'green apple', 0],
    ['🐶', 'dog', 1],
  ],
  emojiIdMap: new Map([
    ['🍎', 0],
    ['🍏', 1],
    ['🐶', 2],
  ]),
  groups: ['Food', 'Animals'],
}

const sampleIndex: InvertedIndex = {
  keywords: ['apple', 'dog', 'red'],
  postings: [[0, 1], [2], [0]],
}

describe('serializeAsTsModule', () => {
  test('output starts with the auto-generated header', () => {
    const out = serializeAsTsModule(sampleTable, sampleIndex)
    expect(out).toMatch(/^\/\/ AUTO-GENERATED by scripts\/build-index\.ts/)
  })

  test('exports the four runtime arrays', () => {
    const out = serializeAsTsModule(sampleTable, sampleIndex)
    expect(out).toContain('export const groups')
    expect(out).toContain('export const emojis')
    expect(out).toContain('export const keywords')
    expect(out).toContain('export const postings')
  })

  test('payload round-trips through JSON.parse', () => {
    const out = serializeAsTsModule(sampleTable, sampleIndex)
    // Extract the JSON literal between the single quotes of JSON.parse('...')
    const match = out.match(/JSON\.parse\('(.+)'\) as RawData/s)
    expect(match).not.toBeNull()

    const escaped = match![1]
    const unescaped = escaped.replace(/\\'/g, "'").replace(/\\\\/g, '\\')
    const parsed = JSON.parse(unescaped)

    expect(parsed.groups).toEqual(sampleTable.groups)
    expect(parsed.emojis).toEqual(sampleTable.emojis)
    expect(parsed.keywords).toEqual(sampleIndex.keywords)
    expect(parsed.postings).toEqual(sampleIndex.postings)
  })

  test('does not include emojiIdMap (runtime rebuilds it from keywords)', () => {
    const out = serializeAsTsModule(sampleTable, sampleIndex)
    expect(out).not.toContain('emojiIdMap')
    expect(out).not.toContain('exactLookup')
  })

  test('escapes single quotes inside string values', () => {
    const tableWithApostrophe: EmojiTable = {
      emojis: [['🍎', "won't", 0]],
      emojiIdMap: new Map([['🍎', 0]]),
      groups: ["food'n'drink"],
    }
    const out = serializeAsTsModule(tableWithApostrophe, { keywords: [], postings: [] })

    // Each apostrophe in the JSON payload must be backslash-escaped so the
    // surrounding single-quoted string literal stays valid.
    const match = out.match(/JSON\.parse\('(.+)'\) as RawData/s)!
    const escaped = match[1]
    expect(escaped).toContain("\\'")

    // And the escaped payload must still round-trip
    const unescaped = escaped.replace(/\\'/g, "'").replace(/\\\\/g, '\\')
    const parsed = JSON.parse(unescaped)
    expect(parsed.emojis[0][1]).toBe("won't")
  })
})
