import { encodeFrontCoded, encodeListOrder, encodePostings } from './data-codec.ts'
import type { EmojiTable } from './build-emoji-table.ts'
import type { InvertedIndex } from './build-inverted-index.ts'

/**
 * Renders the built index as a TypeScript module. The runtime payload is
 * embedded as a single `JSON.parse(...)` call on a string literal — V8
 * parses this notably faster than the equivalent object/array literal.
 *
 * Two compaction techniques shrink the wire payload:
 *
 * - **Front-coded keywords** (`keywordsFC`) — sorted strings stored as
 *   `[sharedPrefixLen, suffix]` tuples, exploiting heavy prefix overlap
 *   in a sorted dictionary.
 * - **Delta + varint postings** (`postingsDV`) — sorted ID lists stored
 *   as base64-packed LEB128 varints over consecutive deltas.
 * - **Curated concept order** (`conceptOrder`) — concept postings are
 *   stored sorted for delta encoding, plus one digit per ID giving its
 *   curated position.
 * - **Korean names by reference** — each emoji's `koName` is stored as its
 *   index in the keyword list (`-1` when absent), since Hangul text barely
 *   compresses and the keyword list already contains it.
 *
 * See `src/core/data-codec.ts` for the matching decoders.
 *
 * 빌드된 인덱스를 TypeScript 모듈로 직렬화. 런타임 payload는 문자열 리터럴
 * 위에 `JSON.parse(...)` 한 번 호출로 임베드 — V8이 동등한 object/array
 * 리터럴보다 눈에 띄게 빠르게 파싱.
 *
 * 두 가지 컴팩션 기법으로 wire payload 절감:
 *
 * - **Front-coded keywords** (`keywordsFC`) — 정렬된 문자열을
 *   `[공유prefix길이, 나머지]` 튜플로 저장. 정렬된 사전의 prefix 중복을 활용.
 * - **Delta + varint postings** (`postingsDV`) — 정렬된 ID 리스트를 연속
 *   차이값에 대한 base64-packed LEB128 varint로 저장.
 * - **개념어 큐레이션 순서** (`conceptOrder`) — 개념어 postings는 delta
 *   인코딩을 위해 정렬해 저장하고, ID마다 큐레이션 위치를 숫자 하나로 기록.
 * - **한국어 대표명 참조** — 각 이모지의 `koName`을 키워드 목록 내 인덱스로
 *   저장(없으면 `-1`). 한글 텍스트는 거의 압축되지 않고, 키워드 목록에 이미
 *   포함되어 있으므로.
 *
 * 짝이 되는 디코더는 `src/core/data-codec.ts` 참조.
 *
 * @see https://v8.dev/blog/cost-of-javascript-2019
 */
export function serializeAsTsModule(
  table: EmojiTable,
  index: InvertedIndex,
  popularity: number[] = [],
): string {
  const keywordIds = new Map(index.keywords.map((kw, i) => [kw, i]))
  const payload = JSON.stringify({
    groups: table.groups,
    emojis: table.emojis.map(([emoji, name, groupId, koName]) => [
      emoji,
      name,
      groupId,
      keywordIds.get(koName) ?? -1,
    ]),
    keywordsFC: encodeFrontCoded(index.keywords),
    postingsDV: encodePostings(index.postings),
    conceptTermsFC: encodeFrontCoded(index.conceptTerms),
    conceptPostingsDV: encodePostings(
      index.conceptPostings.map((ids) => [...ids].sort((a, b) => a - b)),
    ),
    conceptOrder: encodeListOrder(index.conceptPostings),
    popularity,
  })
  const escaped = payload.replace(/\\/g, '\\\\').replace(/'/g, "\\'")

  return `// AUTO-GENERATED by scripts/build-index.ts — do not edit.
// Run \`pnpm build:index\` to regenerate.

interface RawData {
  groups: string[];
  emojis: Array<[emoji: string, name: string, groupId: number, koNameId: number]>;
  keywordsFC: Array<[sharedPrefixLen: number, suffix: string]>;
  postingsDV: string;
  conceptTermsFC: Array<[sharedPrefixLen: number, suffix: string]>;
  conceptPostingsDV: string;
  conceptOrder: string;
  popularity: number[];
}

const RAW = JSON.parse('${escaped}') as RawData;

export const groups = RAW.groups;
export const emojis = RAW.emojis;
export const keywordsFC = RAW.keywordsFC;
export const postingsDV = RAW.postingsDV;
export const conceptTermsFC = RAW.conceptTermsFC;
export const conceptPostingsDV = RAW.conceptPostingsDV;
export const conceptOrder = RAW.conceptOrder;
export const popularity = RAW.popularity;
`
}
