import type { EmojiTable } from './build-emoji-table.ts'
import type { InvertedIndex } from './build-inverted-index.ts'

/**
 * Renders the built index as a TypeScript module. The runtime payload is
 * embedded as a single `JSON.parse(...)` call on a string literal — V8
 * parses this notably faster than the equivalent object/array literal.
 *
 * 빌드된 인덱스를 TypeScript 모듈로 직렬화. 런타임 payload는 문자열 리터럴
 * 위에 `JSON.parse(...)` 한 번 호출로 임베드 — V8이 동등한 object/array
 * 리터럴보다 눈에 띄게 빠르게 파싱.
 *
 * @see https://v8.dev/blog/cost-of-javascript-2019
 */
export function serializeAsTsModule(table: EmojiTable, index: InvertedIndex): string {
  const payload = JSON.stringify({
    groups: table.groups,
    emojis: table.emojis,
    keywords: index.keywords,
    postings: index.postings,
  })
  const escaped = payload.replace(/\\/g, '\\\\').replace(/'/g, "\\'")

  return `// AUTO-GENERATED by scripts/build-index.ts — do not edit.
// Run \`pnpm build:index\` to regenerate.

interface RawData {
  groups: string[];
  emojis: Array<[emoji: string, name: string, groupId: number]>;
  keywords: string[];
  postings: number[][];
}

const RAW = JSON.parse('${escaped}') as RawData;

export const groups = RAW.groups;
export const emojis = RAW.emojis;
export const keywords = RAW.keywords;
export const postings = RAW.postings;
`
}
